# SonarCloud configuration

sonar.organization=weirdapps
sonar.projectKey=weirdapps_MarketHours
sonar.projectName=MarketHours

sonar.sources=MarketHours,Packages/MarketHoursCore/Sources,scripts
sonar.tests=Packages/MarketHoursCore/Tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/*.xcassets/**
